<!DOCTYPE html>
<html lang="en">
 <link href="{{ '/style.css' | relative_url }}" rel="stylesheet">
 <link rel="stylesheet" href="../style.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="../index.html">PHYS S-12: Introduction to Digital Fabrication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="../index.html">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../about.html">About</a>
        </li>
      </ul>
    </div>
  </nav>
  
<body>
<br>
<br>
<div class="bodytext"><h4>Week 2: 2D Design and Cutting</h4></div>

<div class="spacer"></div>

<p>
  For Week 2, we focused on learning the basics of Fusion 360, building a press-fit construction kit with kerf taken into account, 
  and then modeling household objects or components for our final project. Let's start with the basics. 
</p>

<p>
  <img src="./001.png" class="imagedoc">
</p>

<p>
  <br>
  First, I drew a 40mm x 40mm rectangle in sketch mode and added 3mm central slits on each side, per the PHYS S-12 tutorial.
</p>

 <p>
  <img src="./002.png" class="imagedoc">
 </p>

 <p>Next, I included a 3mm fillet on each of the outer corners of the slits, 
  for smoother operation, again per the PHYS S-12 tutorial. 
  </p>

  <p>At this point, I ventured into experimenting with my own components. 
  My initial thought was that a pyramid construction would be a good starting point, 
  since it involves square pieces and triangle pieces, plus a connector piece. 
  </p>

<p>Let's start by determining the geometry of the pyramid so that we know the sizes for the press kit pieces. 
  A square pyramid floor keeps things tidy.. We already were looking at a square piece, so we can try four 40mm x 40mm square pieces for the floor. 
 </p>


  <div class="bodytext">
    <img src="./003.png" class="imagedoc">
  </div>
  <div class="bodytext">
    Looking at this diagram  (source: https://www.cuemath.com/geometry/square-pyramid/ ) for visualization purposes, 
    we can see that it's necessary to decide how to segment the pieces for the sides now. 
    They could be bisected, per the above, or each of the three sides could be made up of four triangular segments: 
    </div> 

<div class="bodytext">
  <img src="./004.png" class="imagedoc">
  </div>
  <div class="bodytext">
  (image source: https://commons.wikimedia.org/wiki/File:Equilateral_triangle_cut_to_4.svg )
  <br><br>

   The latter, with four triangular pieces per side, is more versatile--plus it's a Triforce--so we'll go with that.
    Since the base sides are 80mm each, each triangle's sides should be 40mm, and we'll need 16 triangles (four per side). 
    We'll need to determine where the connector points should be, optimally. So let's start with a sketch. 
</div>

<div class="bodytext">
  <img src="./005.png" class="imagedoc">
  </div>
  <<div class="bodytext">
  We have some considerations for the connector piece. But for now, let's move on to designing the triangle piece. 
  I've referenced another project to determine the material thickness of 3.8mm and a kerf of 0.2mm. 
  However, if we adapt the PHYS S-12 tutorial to the triangle piece, by setting an offset of 10mm for the slit,
   this barely leaves any remaining material on the interior of the triangle. 
   As such, we will move forward with a 5mm depth notch. Midpoint lines are set using construction lines,
    they are offset by (thickness-kerf)/2 and then mirrored. 
</div>

<div class="bodytext">
  <img src="./006.png" class="imagedoc">
</div>

<div class="bodytext">
  <img src="./007.png" class="imagedoc">
  </div>

  <div class="bodytext">
  At this point, we want to fillet the slits. However, a 3mm fillet setting produced unusable results for this notch depth, so we'll go with a more modest 1mm fillet setting. 
</div>

<div class="bodytext">
  <img src="./008.png" class="imagedoc">
</div>

<p>
  For this test print, the width of the slits ended up being too large to fit snugly, 
  so the Fusion 360 file needed to be adjusted. The kerf setting was increased modestly to 0.4mm, 
  but that didn't make a noticeable difference--clearly there was an issue whereby the laser is going over each cut twice, 
  significantly increasing the kerf. For now, I increased the kerf setting to 10mm to compensate. 
<br><br>
This produced a more usable set of slits. 
</p>

<div class="bodytext">
  <img src="./009.png" class="imagedoc">
  </div>

  <p>
  For the final print, we'll increase kerf further to 1.2mm for snugness.
</p>
<p>Now back to the square for V2, with 5mm offset and 1.2mm kerf. We'll give it a 1mm fillet as well for uniformity. 
</p>

<div class="bodytext">
  <img src="./010.png" class="imagedoc">
</div>

<div class="bodytext">
  <img src="./011.png" class="imagedoc">
</div>

<div class="bodytext">
  <img src="./012.png" class="imagedoc">
</div>

<p>
  Here are the parameters. </p>

<p>Next, we have to redo the triangle piece to the correct size to match the square, so a 50mm version with identical slits to the square is created below.
</p>

<div class="bodytext">
  <img src="./013.png" class="imagedoc">
</div>

<p>
  <img src="./014.png" class="imagedoc">
</p>

<div class="bodytext">
  Now that the big triangle is finished, we need a snug connector. It should be the width of the square and triangle slits (accounting for kerf). Before kerf, it's 4.60mm. 
</div>

<div class="bodytext">
  <img src="./015.png" class="imagedoc">
</div>

<p>
  Considering the filleting, we're looking at a depth of 5mm, if the connector is filleted too of course. 
  </p>
  <p><img src="./016.png" class="imagedoc">
  </p>

<p>
  We will need prongs on each side with a length of 5mm each, plus enough material in between for stability. 2mm should be enough. 
</p>>

<p> 12mm (5mm x2 + margin) width and 7mm (5mm + margin) length, with a 1mm fillet. 
</p>

<div class="bodytext">
  <img src="./017.png" class="imagedoc">
</div>

<div class="bodytext">
  Turns out, though, that the fillet is not feasible on a connector of this size, and the dimensions are too small to remain intact as a support structure. 
</div>

<p>
  Time for a bigger H. </p>

  <p><img src="./018.png" class="imagedoc">
  </p>

<p>
  Finally, I decided to make the connector more versatile after determining that the structural integrity would remain sound with four slits. 
  The shape allows for a more flush fit on two of the corners and a firmer fit with a bit more spacing on the other two corners. 
  </p>
  <p>
  <img src="./019.png" class="imagedoc">
  </p>

<p>
  20mm length, 15mm width, 3.8mm depth.
  <br><br>
  4mm wide slits, 5.5mm deep slits on two sides, 5mm slits on two other sides. No fillet this time. 
</p>

<p>
Let's move on to printing and assembly of the above.
</p>

  <p><img src="./020.png" class="imagedoc">
  
  </p>

<p>
  <img src="./021.png" class="imagedoc">
</p>

<p>
  <img src="./025.png" class="imagedoc">
  </p>
  <p>
  <img src="./022.png" class="imagedoc">
  
  </p>


<p>
  Use the connectors to attach the base squares into a larger square. 
  </p>
  <p>
  <img src="./023.png" class="imagedoc">
  </p>

<div class="bodytext">
  <img src="./024.png" class="imagedoc">
</div>


<p>
  Attach connectors to the slits to assemble the pyramid. 
  </p>
  <p>
  <img src="./026.png" class="imagedoc">
  
  </p>

<div class="bodytext">
  <img src="./027.png" class="imagedoc">
</div>

<div class="bodytext">
  And now, the finished model. 
  <br><br>
</div>

<div class="bodytext">
  <img src="./030.png" class="imagedoc">
</div>

<div class="bodytext">
  <img src="./031.png" class="imagedoc">
</div>

<p>
Here are the Fusion 360 files for the pieces:
</p>
<p><a href="./square.f3d">Square</a>
</p>
<p><a href="./triangle.f3d">Triangle</a>
</p>
<p>
<a href="./connector.f3d">Connector</a>
</p>


<p></p>
<p>Now we have to  model household items. I chose my water bottle to start with. First, I took some measurements. 
</p>

<div class="bodytext">
  <img src="./028.png" class="imagedoc">
</div>

<div class="bodytext">
  <img src="./029.png" class="imagedoc">
</div>

<p>
Next, I looked at a tutorial on how to model a water bottle in Fusion 360: https://www.youtube.com/watch?v=s5tRWYkxu9o
</p>

<p>
One interesting item of note is using the equal command in F360, which will set elements equal to each other if any of the elements change. This is useful for modeling ridges in the water bottle.
The same can be done with the horizontal/vertical constraint tool, to keep lines aligned on those axes. 
</p>

<p>
Anyway, let's begin sketching the bottle using the measured dimensions. We'll start with a vertical line from the origin using the length of the bottle (262mm), then use a horizontal line from the 
top to create the cap (43.05mm diameter, 30.18mm length). Now we'll create another horizontal line from the bottom of the bottle using the bottle diameter (70.97mm), and create a smooth curve taper 
from the bottle to the cap using the spline tool. 

<br><br>We'll also parameterize the dimensions and use the diameters/2 for the radii. 
</p>

<p>
Next, we'll finish the sketch and use the Revolve tool to 3D model it. 
</p>

<div class="bodytext">
  <img src="./032.png" class="imagedoc">
</div>

<div class="bodytext">
  <img src="./033.png" class="imagedoc">
</div>


<p>
  Voila, a bottle.
</p>

<div class="bodytext">
  <img src="./034.png" class="imagedoc">
</div>

<p>
 Here's the Fusion 360 file for the bottle:
 </p>
<p><a href="./bottle.f3d">Bottle</a>
</p>

<p>
  For a second model, we'll look at a can. 
</p>
  <p><img src="./035.png" class="imagedoc">
  </p>
  <p>The diameter is 116.47mm and the height is 153.12mm. There are five ridges, starting about 39mm from the top of the can.
  </p>


<p>
  We'll sketch out the shape in Fusion 360, with the five symmetrical ridges starting at 39mm from the top created using the line tool. We'll make sure that it's an enclosed shape. 
  </p>>
  <p><img src="./036.png" class="imagedoc">
  </p>

<p>
  Then revolve around the y axis. 
  </p>>
  <p><img src="./037.png" class="imagedoc">
  </p>



<p>
  Fusion 360 file for the can:
  </p>
  <p>
 <a href="./can.f3d">Can</a>
  </p>
</body>


</html>